export default function About() {
	return (
		<div className="mx-auto md:w-800 w-full flex justify-center text-blueLike bg-zinc-100" id="about">
			<div id="about" className="px-4 container w-5/6 max-w-4xl mt-40 pb-20 text-l lg:text-l">
				<h1 className="text-4xl  font-semibold">About</h1>
				<br></br>

				<h2 className="lg:text-xl  font-semibold"> What is Alphy?</h2>
				<br></br>
				<p className="text-xl">
					{' '}
					Alphy aims to help users meaningfully interact with the information present in online audiovisual content with the
					help of artificial intelligence. Upon submitting the link for a YouTube video or Twitter Spaces, Alphy gives you:
					<ol className="mt-5">
						<li className="pt-3">
							<strong> • A highly accurate transcript </strong> of the content with timestamps, ready to use on any online video outlet.
						</li>
						<li className="pt-3">
							<strong> • An AI-powered chatbot generated on top of the content transcript </strong> that allows you to ask questions and get AI-generated answers, unlocking an immense information capture potential for your the users.
						</li>
						<li className="pt-3">
							<strong> • The summary and TL:DR of the content</strong> for you to cut down on time to get the most relevant information.</li>
					</ol>
				</p>
				<br></br>
				<br></br>
				<h2 className="lg:text-xl  font-semibold"> What can you do with Alphy?</h2>
				<br></br>
				<p className="text-xl">
					• You can ask questions to a video or recording to get the most relevant answers presented by the
					content.
					<br></br>
					<br></br>• You can get a detailed summary of the content as well as a TL:DR version of that summary
					that lays out the key takeaways of the video.
					<br></br>
					<br></br>• You can access high quality transcripts that are far more accurate than the ones that are autiomatically generated by YouTube and Twitter.

				</p>
				<br></br>
				<br></br>
				<h1 className="text-2xl  font-semibold">Quick info about the product:</h1>
				<br></br>
				<p className="text-xl">
					• You make a work request by signing in and submitting a YouTube video or Twitter Spaces link to
					Alphy.
					<br></br>
					{/*                     <br></br>
                    • There is a limit on the number of submissions you can make a day to decrease the bloat.
                    <br></br> */}
					<br></br>• Currently, Alphy works best in English. We are working on supporting other
					languages. Meanwhile you may encounter some errors with non-English content.
					<br></br>

					<br></br>• Transcription process may take some time. We will notify you via email when your work is
					ready.

					<br></br>
					<br></br>
					•  Please make sure the duration of the content does not exceed 3 hours. Otherwise, Alphy won't be able to process the content. We are working on increasing this limit.
					<br></br>
					<br></br>
					• Once the content is processed, it is public. Anyone can read and ask questions without signing in.
					<br></br>
					<br></br>• If you see a video that has a really bad transcription (wrong language, missing
					punctuations, etc.), please ping us via the socials we shared at the bottom of the page.
				</p>
				<br></br>
				<br></br>
			</div>
		</div>
	);
}
