



export default function About() {

    return (
        <div className="flex justify-center text-blueLike">

            <div id="about" className="px-4 container w-4/6 pt-20 pb-20 text-l lg:text-l">
                <br></br><br></br>
                <h1 className="text-4xl  font-semibold">About


                </h1>
                <br></br>

                <h2 className="lg:text-xl  font-semibold"> What is it?</h2>
                <br></br>
                <p> Alphy uses artificial intelligence to transcribe and summarize on an audio-based content and offers semantic research on the transcript for you to talk with the content. It aims to help users meaningfully interact with the speeh-based information on the Internet.
                </p>
                <br></br>
                <br></br>
                <h2 className="lg:text-xl  font-semibold"> What can I do with Alphy?</h2>
                <br></br>
                <p>• You can do semantic research on the video transcript, asking real questions and getting real answers. or search for a specific topic.

                    <br></br><br></br>• You can get a detailed summary of the content as well as a TL:DR version of that summary that lays out the key takeaways of the video.

                    <br></br><br></br>• The transcripts auto-generated by YouTube and Twitter Spaces are not ideal. You can get a decent transcript with Alphy.</p>
                <br></br>
                <br></br>
                <h1 className="text-2xl  font-semibold">Quick info about the product:</h1>
                <br></br>
                <p>• You make a work request by signing in and submitting a YouTube video or Twitter Spaces link to Alphy.
                    <br></br>
                    <br></br>
                    • There is a limit on the number of submissions you can make a day to decrease the bloat.
                    <br></br>
                    <br></br>
                    • Currently, Alphy only supports English. We are working on supporting other languages.
                    <br></br>
                    <br></br>
                    • Transcription process may take some time. We will notify you via email when your work is ready.

                    <br></br>
                    <br></br>
                    • You can read it all you want. Once a video is processed, it is public. Everyone can read it without signing in. You need to sign in to submit links and ask questions.
                    <br ></br>
                    <br></br>
                    • If you see a video that has a really bad transcription (wrong language, missing punctuations, etc.), please ping us on Discord, Twitter or via info@alphy.tech.</p>
                <br></br>
                <br></br>

            </div>
        </div>
    )


}