



export default function About() {

    return (

        <div className="text-mainText px-4 container mb-20 pb-30 text-l   lg:text-xl">

            <h1 className="font-semibold text-3xl">About Alphy

            </h1>      <br></br>
            <br></br>
            <h2 className="lg:text-2xl"> What is it?</h2>
            <br></br>
            <p> Alphy uses artificial intelligence to transcribe and summarize YouTube videos and Twitter Spaces and offers semantic search on the transcript for you to talk with the content. It aims to allow users to meaningfully interact with the speeh-based information on the Internet.
            </p>
            <br></br>
            <br></br>
            <h2 className="lg:text-2xl"> What can I do with Alphy?</h2>
            <br></br>
            <p>The transcripts auto-generated by YouTube and Twitter Spaces are not ideal. You can get a decent transcript with Alphy.

                <br></br>You can get a detailed summary of the video and get the main idea in a short amount of time.

                <br></br>You can converse with a video.</p>
            <br></br>
            <br></br>
            <h1 className="font-semibold text-3xl">Quick info about the product:</h1>
            <br></br>
            <p> • You can read it all you want. Once a video is processed, it is public. Everyone can read it without signing in.
                <br></br>
                <br></br>
                • You make a work request by signing in and submitting a YouTube video or Twitter Spaces link to Alphy.
                <br></br>
                <br></br>
                • Currently, Alphy only supports English. We are working on supporting other languages.
                <br></br>
                <br></br>
                • There is a limit on the number of submissions you can make a day to decrease the bloat.
                <br></br>
                <br></br>
                • Transcription process may take some time. We will notify you via email when your work is ready.
                <br ></br>
                <br></br>
                • If you see a video that has a really bad transcription (wrong language, missing punctuations, etc.), please ping us on Discord, Twitter or via hello@alphy.tech.</p>
            <br></br>
            <br></br>

        </div>

    )


}